[package]
name = "eze"
version = "0.1.0"
edition = "2021"
description = "A ls-like file system representer"
license = "MIT"
repository = "https://github.com/Behruz-s-organization/"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
owo-colors = "4.3.0"
chrono = "0.4"
uzers = "0.12.2"
